spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route: #路由配置规则
      path: /uac/**  #将这个下的请求,路由到 service-id=passcloud-provider-uac 服务上去进行处理
      sensitiveHeaders:
#      strip-prefix: false
      service-id: paascloud-provider-uac #服务提供者ID,可以进行负载均衡, 如果是url的话,则没法负载均衡
      ribbon: #对所有的服务配置,如果单独对于一种服务,前面表明服务名称  如hello-service.ribbon.ConnectTimeout=600
        eager-load:
          enabled: true
        MaxAutoRetries: 1 #对当前实例的重试次数
        MaxAutoRetriesNextServer: 2 #切换实例的重试次数
        OkToRetryOnAllOperations: false #对所有操作请求都进行重试
        ConnectTimeout: 100000000 #设置连接超时时间
        ReadTimeout: 100000000 #设置读取超时时间
    adou-route: #路由配置规则
      path: /adou/**  #将这个下的请求,路由到 service-id=passcloud-provider-uac 服务上去进行处理
      sensitiveHeaders:
#      strip-prefix: false
      service-id: paascloud-adou #服务提供者ID
      ribbon: #对所有的服务配置,如果单独对于一种服务,前面表明服务名称  如hello-service.ribbon.ConnectTimeout=600
        eager-load:
          enabled: true
        MaxAutoRetries: 1 #对当前实例的重试次数
        MaxAutoRetriesNextServer: 2 #切换实例的重试次数
        OkToRetryOnAllOperations: false #对所有操作请求都进行重试
        ConnectTimeout: 10000 #设置连接超时时间
        ReadTimeout: 10000 #设置读取超时时间
    mdc-route:
      path: /mdc/**
      sensitiveHeaders:
      service-id: paascloud-provider-mdc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 100000000
        ReadTimeout: 100000000
    omc-route:
      path: /omc/**
      sensitiveHeaders:
      service-id: paascloud-provider-omc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    opc-route:
      path: /opc/**
      sensitiveHeaders:
      service-id: paascloud-provider-opc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    mall-route:
      path: /mall/**
      sensitiveHeaders:
      service-id: paascloud-web-mall
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    tpc-route:
      path: /tpc/**
      sensitiveHeaders:
      service-id: paascloud-provider-tpc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true
  
security:
  oauth2:
    client:
      clientId: paascloud-client-gateway
      clientSecret: paascloudClientSecret
      access-token-uri: http://paascloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://paascloud-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://paascloud-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://paascloud-provider-uac:8000/oauth/token_key

paascloud:
  enableSqlLogInterceptor: false
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
  generate-routes: omc-route,mdc-route,opc-route,tpc-route,uac-route
# 忽略某些路由生成
#  ignore-routes: